---
title: "SU_25_River_Rockfish_Proj_Fecundity_V0.2"
author: "River Mckegney"
date: "`r Sys.Date()`"
output: html_document
---





# pH Stat Tests

Weight adJ Fecundity no Atresia 
```{r}

# Fancy lmer model
pH_fancy_lm <- lm(pH ~ Ambient.Or.OAH * Weight_Adjusted_Fecundity_Fecundity.Mean_Weight, data = Fecundity_No_Atresia_Samples)
summary(pH_fancy_lm)

pH_fancy_lm_sim_res_plot <- simulateResiduals(fittedModel = pH_primary_wadj_fec_lm)
plot(pH_fancy_lm_sim_res_plot)

visualize(pH_fancy_lm)


```



```{r}
# ph
# Primary Samples

# Linear Model 

# Install flexplot
# devtools::install_github("dustinfife/flexplot", ref="development")
require(flexplot)

pH_primary_lm <- lm(pH ~ Pregnant.Or.Atresia * Ambient.Or.OAH, data = Primary_Samples)

# p-value significant if (a < 0.1 or a < 0.05)
summary(pH_primary_lm)

pH_primary_lm_res_plot <- simulateResiduals(fittedModel = pH_primary_lm)
plot(pH_primary_lm_res_plot)

# For shapiro test
pH_primary_lm_res <- residuals(pH_primary_lm)


# Linear Model with weight adjusted funcundity

pH_primary_wadj_fec_lm <- lm(pH ~ Weight_Adj_Fec_With_Ateresia_Zeros, data = Primary_Samples)
summary(pH_primary_wadj_fec_lm)

visualize(pH_primary_wadj_fec_lm, plot = "model")

pH_primary_lwadj_fec_sim_res_plot <- simulateResiduals(fittedModel = pH_primary_wadj_fec_lm)
plot(pH_primary_lwadj_fec_sim_res_plot)


# Residuals Plot (if significant)
# ggplot with geom_smooth(aes(x=,y=)), method = "lm")

pH_primary_wadj_fec_lm_scatterplot <- ggplot(data = Primary_Samples) + 
  geom_point(aes(x = pH, y = Weight_Adj_Fec_With_Ateresia_Zeros), colour = "black") +
  geom_smooth(aes(x = pH, y = Weight_Adj_Fec_With_Ateresia_Zeros), method = "lm") +
  labs(title = "pH", x = "pH", y = "Weight Adjusted Fecundity") +
  scale_y_continuous() + 
  theme_classic() +
  facet_wrap(~ Ambient.Or.OAH) +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        legend.background = element_rect(fill = "white", color = "black"),
        plot.title = element_text(size = 25, hjust = 0.5),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))

print(pH_primary_wadj_fec_lm_scatterplot)

ggsave(filename = "data-images/pH_primary_wadj_fec_lm_scatterplot.pdf", plot = pH_primary_wadj_fec_lm_scatterplot, device = "pdf")

ggsave(filename = "data-images/pH_primary_wadj_fec_lm_scatterplot.png", plot = pH_primary_wadj_fec_lm_scatterplot, device = "png")

```